---
title: "Revisión de textos"
always_allow_html: yes
author:
- Autor Nicole Aising
- Autor Lucas Palazzo
date: "Mayo 2019"
output: 
  beamer_presentation:
    theme: classic
institute:
- EII
subtitle: Detalle
header-includes:
- \usepackage{pgf,tikz}
- \usetikzlibrary{patterns}
- \usetikzlibrary{arrows}
- \usepackage{pgfplots}
---

# Revisión literatura:
-¿Pueden las corporaciones producir bienes sociales mientras operan dentro de los límites del capitalismo basado en el mercado?  
-¿Qué clase de criaturas somos?  
-Desarrollo del individuo  
-Una mejor manera de elegir presidentes  
-Sistema de juicio mayoritario, matemáticas para las urnas  
-Interacciones salariales entre sectores público y privado  

# Revisión de literatura semana pasada
-Uso de la ciencia de la conservación para avanzar en la responsabilidad corporativa de la biodiversidad  
-Representación de los principios de sostenibilidad en las declaraciones de misión y en las páginas de inicio de las organizaciones más grandes del mundo


# Revisión de literatura semana actual

1- Mejores prácticas para el compromiso de las coorporaciones en cuanto a la diversidad: un marco de trabajo para organizar.

Las operaciones corporativas pueden tener impactos significativos en la biodiversidad. 
															
-La literatura ha pasado por alto el análisis de las prácticas organizativas que subyacen en el compromiso corporativo con la biodiversidad. se analiza el impacto en la biodiversidad pero no a las prácticas que subyacen.
 
# 1.- Mejores prácticas para el compromiso de las coorporaciones en cuanto a la diversidad: un marco de trabajo para organizar

-Datos

Análisis sistemático de las prácticas de sostenibilidad informadas por 163 empresas mineras y forestales cuyas operaciones representan un alto riesgo para la biodiversidad. Según un estudio reciente de 126 empresas de sectores con impactos significativos en la biodiversidad, solo el 32% de estas empresas han implementado una política o programa formal en esta área ( CERES, 2014 ).Global Reporting Initiative (GRI), que incluyen información sobre la gestión de la biodiversidad.
 
# 1.- Mejores prácticas para el compromiso de las coorporaciones en cuanto a la diversidad: un marco de trabajo para organizar

-¿cuales son las mejores prácticas de conservación de la biodiversidad de las compañías cuyas operaciones presentan altos riesgos para la biodiversidad?
 
Se requieren cambios significativos y la implementación de prácticas gerenciales específicas. Cuando están bien documentados, los informes de sostenibilidad pueden ayudar a identificar y analizar las mejores prácticas para el medio ambiente, que pueden ser útiles para los administradores e investigadores por igual.

# 2.-Integración de los principios de la economía social y solidaria en el diseño sostenible de bienes de consumo

- La esencia del movimiento de la ESS es la transformación social, la coherencia con sus valores y principios, y la racionalidad económica basada en la solidaridad, la sostenibilidad y unas relaciones horizontales y cooperativas que persiguen la satisfacción de necesidades y el desarrollo humano, individual y comunitario, en vez de la maximización del beneficio económico.

# 3.- La economía social ante los paradigmas económicos emergentes: innovación social, economía colaborativa, economía circular, responsabilidad social empresarial, economía del bien común, empresa social y economía solidaria.

-Objetivo: Analizar los conceptos emergentes y compararlos con el concepto de economía social.  
-Hipótesis: En ciencias sociales los cambios de paradigmas o procesos de revolución científica se producen de modo simultáneo a las grandes transformaciones socioeconómicas y a las grandes crisis. Y estos cambios de paradigma van acompañados con un nuevo lenguaje y conceptos.  
-Nacionalizacion, privatización, "comunitarización".

# Economia social
- La economía social conforma un espacio de la realidad económica integrado por formas organizativas privadas creadas por las personas para dar respuesta a sus propias demandas sociales, a sus problemas sustantivos y a sus aspiraciones sociales. Su carácter social y privado las sitúa en una lógica económica y decisional bien diferenciada de la de las empresas privadas tradicionales, basadas en la lógica del capital.

# Nociones emergentes.
-Innovación social  
-Economía colaborativa  
-Economía circular  
-Responsabilidad social empresarial  
-Economía del bien común  
-empresa social   
-economía solidaria 

# Ánalisis comparativo de las nociones emergentes
-Nociones ligadas a ámbitos centrales de crisis y transformación del sistema: innovación social, economía colaborativa y economía circular.  
-Nociones ligadas a la reorientación de los objetivos de modo de funcionamiento de las economias con mecanismos de evaluación e incentivo: RSE y economía del bien común.  
-Nociones ligadas a las nuevas formas de entender la práctica ecónomica y la forma de hacer empresa: empresa social, economía solidaria.

# Conclusiones
-los nuevos paradigmas aparecidos en el contexto de crisis de legitimidad del modelo economico son complementarios e incluso revitalizadores respecto al concepto de la economía social.


# Preguntas por responder.
-¿Cómo llevar la economía social al contexto local ?





